# Generated by Django 5.2.8 on 2025-11-28 20:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myphotoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myphoto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myphoto',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
