# Generated by Django 5.2.8 on 2025-11-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myphotoapp', '0002_myphoto_uploaded_at_alter_myphoto_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.AlterField(
            model_name='myphoto',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
