# Generated by Django 5.2.8 on 2025-11-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myphotoapp', '0003_myvideo_alter_myphoto_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='myvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
