# Generated by Django 5.2.8 on 2025-11-29 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myphotoapp', '0004_myvideo_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myvideo',
            name='thumbnail',
        ),
    ]
