# Generated by Django 5.2.8 on 2025-11-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myphotoapp', '0005_remove_myvideo_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myvideo',
            name='video_file',
        ),
        migrations.AddField(
            model_name='myvideo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='myvideo',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
