# Generated by Django 5.2.8 on 2025-11-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myphotoapp', '0006_remove_myvideo_video_file_myvideo_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myphoto',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='myphoto',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
