# Generated by Django 5.2.8 on 2025-11-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myphotoapp', '0007_remove_myphoto_uploaded_at_myphoto_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myphoto',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
