# Generated by Django 5.2.8 on 2025-11-29 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myphotoapp', '0008_myphoto_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myphoto',
            name='description',
        ),
    ]
