# Generated by Django 5.2.8 on 2025-11-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myphotoapp', '0009_remove_myphoto_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
